name: Destroy Serverless App Infra

on:
  workflow_dispatch:  # Allows you to trigger manually from GitHub UI

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
        
    - name: Terraform Destroy
      run: terraform destroy -auto-approve
