name: Terraform Serverless App

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose Terraform action'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Zip Lambda Function
        run: |
          cd lambda_function
          zip -r app.zip app.py
          cd ..

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Run Terraform
        run: |
          if [ "${{ github.event.inputs.action }}" == "apply" ]; then
            echo "Deploying infrastructure..."
            terraform plan
            terraform apply -auto-approve

            echo "Uploading frontend to S3..."
            aws s3 cp frontend/index.html s3://my-serverless-frontend-bucket/index.html --acl public-read

          elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
            echo "Destroying infrastructure..."
            terraform destroy -auto-approve || echo "Some resources may not exist, continuing..."
          else
            echo "Unknown action: ${{ github.event.inputs.action }}"
            exit 1
          fi
